import chainlit as cl
import httpx
import logging
import sys

# =========================================================
# CLOUDWATCH LOGGING CONFIGURATION
# =========================================================
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)] # Ensures logs go to ECS/CloudWatch
)
logger = logging.getLogger("CHATBOT")

LAMBDA_URL = "https://h2hyz4mqjmlrp5fjhdpj65hiji0dxbyo.lambda-url.us-west-2.on.aws/"
SESSION_MEMORY = {}

@cl.on_message
async def main(message: cl.Message):
    user_id = cl.user_session.get("id", "default_user")
    user_query = message.content.strip()

    # Log the incoming user message
    logger.info(f"User({user_id}) Query: {user_query}")

    if user_id not in SESSION_MEMORY:
        SESSION_MEMORY[user_id] = {}

    # Context handling (The fix for pronouns like 'her')
    last_answer = SESSION_MEMORY[user_id].get("last_answer", "")
    final_query = f"Context: {last_answer}\nUser: {user_query}" if last_answer else user_query

    payload = {"query": final_query}

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            logger.info(f"Calling Lambda for User({user_id})...")
            
            response = await client.post(LAMBDA_URL, json=payload)
            
            # Log the raw response for CloudWatch debugging
            logger.info(f"Lambda Response Status: {response.status_code}")
            
            res_data = response.json()
            
            # Log the SQL generated by the Lambda (Principal Engineer visibility)
            if "sql" in res_data:
                logger.info(f"Generated SQL: {res_data['sql']}")

        if response.status_code == 200:
            answer = res_data.get("response") or res_data.get("body") or str(res_data)
            SESSION_MEMORY[user_id]["last_answer"] = answer
            
            await cl.Message(content=answer).send()
        else:
            logger.error(f"Lambda failed with body: {response.text}")
            await cl.Message(content=f"❌ Error: {response.status_code}").send()

    except Exception as e:
        logger.exception("An unexpected error occurred during the Lambda call")
        await cl.Message(content="⚠️ A technical error occurred. Please try again.").send()